spring:
 application:
  name: shopping-cart
 datasource:
   url: jdbc:mysql://localhost:3306/shoppingcart
   username: root
   password: NewPassword123!
 jpa:
  hibernate:
    ddl-auto: update
  show-sql: true

