spring:
  application:
    name: shopping-cart
  profiles:
    active: dev
jwt:
  secret: ${JWT_SECRET}
  accessTokenExpiration: 900      # 15 minutes
  refreshTokenExpiration: 604800  # 7 days

stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}
