spring:
  application:
    name: shopping-cart

  datasource:
    url: jdbc:mysql://localhost:3306/shoppingcart
    username: root
    password: NewPassword123!

  flyway:
    baseline-on-migrate: true

  mvc:
    log-request-details: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET}
  accessTokenExpiration: 900      # 15 minutes
  refreshTokenExpiration: 604800  # 7 days

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE